version: '3.9'
services:
    nginx:
        depends_on:
            - wordpress
        env_file: .env
        build: ./requirements/nginx
        container_name: nginx
        volumes:
            - wp:/var/www/wordpress
        ports:
            - '443:443'
        networks:
            - web
    wordpress:
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        container_name: wordpress
        restart: always
        volumes:
            - wp:/var/www/wordpress
        env_file:
            - .env
        networks:
            - web

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: on-failure
        env_file: .env
        volumes:
            - db:/var/lib/mysql
        networks:
            - web

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp
 
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db

networks:
  web:
    driver: bridge